# Generated by Django 5.2 on 2025-04-05 13:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('short_text', 'Short Text'), ('long_text', 'Long Text'), ('email', 'Email'), ('choice', 'Choice'), ('file', 'File')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('multiple', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('programming_stack', models.CharField(max_length=255)),
                ('date_responded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_responded'],
            },
        ),
        migrations.CreateModel(
            name='QuestionFileProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('.pdf', 'PDF'), ('.doc', 'Word'), ('.docx', 'Word (new)'), ('.jpg', 'JPEG'), ('.png', 'PNG')], max_length=10)),
                ('max_file_size', models.IntegerField()),
                ('max_file_size_unit', models.CharField(choices=[('kb', 'Kilobytes'), ('mb', 'Megabytes'), ('gb', 'Gigabytes')], max_length=2)),
                ('multiple', models.BooleanField(default=False)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_properties', to='survey.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='survey.question')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='survey.response')),
            ],
        ),
    ]
